import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import HeroSection from "@/components/home/HeroSection";
import ProductsShowingSection from "@/components/home/ProductsShowingSection";
import Hero from "@/components/home/Hero";
import DimensionsPictures from "@/components/home/DimensionsPictures";
import DreamTempleBudget from "@/components/home/DreamTempleBudget";


export default function Home() {
  return (
    <>
      <Head>
        <title>Inadian Stonex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-[80vh] w-full">
        <Hero />

        <DimensionsPictures/>

        <DreamTempleBudget/>

      </div>
    </>
  );
}
